src/java/com/ventas/controlador/CategoriasController.java
package com.ventas.controlador;

import com.ventas.entidades.Categorias;
import com.ventas.controlador.util.JsfUtil;
import com.ventas.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("categoriasController")
@SessionScoped
public class CategoriasController implements Serializable {

    @EJB
    private com.ventas.controlador.CategoriasFacade ejbFacade;
    private List<Categorias> items = null;
    private Categorias selected;

    public CategoriasController() {
    }

    public Categorias getSelected() {
        return selected;
    }

    public void setSelected(Categorias selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CategoriasFacade getFacade() {
        return ejbFacade;
    }

    public Categorias prepareCreate() {
        selected = new Categorias();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
       
        //if(ejbFacade.consultarId(getSelected().getIdCategoria())=="crear"){
            
            //System.out.println("No se puede guardar el registro- repetido");
            
        //}else{
            persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CategoriasCreated"));
            if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        //}
        }


    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CategoriasUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CategoriasDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Categorias> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction == PersistAction.DELETE) {
                    getFacade().remove(selected);
                } else {
                    if (persistAction == PersistAction.CREATE){
                        getFacade().create(selected);
                    }else{
                        getFacade().edit(selected);
                    }
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Categorias getCategorias(java.math.BigDecimal id) {
        return getFacade().find(id);
    }

    public List<Categorias> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Categorias> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Categorias.class)
    public static class CategoriasControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CategoriasController controller = (CategoriasController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "categoriasController");
            return controller.getCategorias(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Categorias) {
                Categorias o = (Categorias) object;
                return getStringKey(o.getIdCategoria());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Categorias.class.getName()});
                return null;
            }
        }

    }

}

src/java/com/ventas/controlador/ClientesController.java
package com.ventas.controlador;

import com.ventas.entidades.Clientes;
import com.ventas.controlador.util.JsfUtil;
import com.ventas.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import org.primefaces.event.map.PointSelectEvent;
import org.primefaces.event.map.StateChangeEvent;

import org.primefaces.model.map.DefaultMapModel;
import org.primefaces.model.map.LatLng;
import org.primefaces.model.map.LatLngBounds;
import org.primefaces.model.map.MapModel;
import org.primefaces.model.map.Marker;



@Named("clientesController")
@SessionScoped
public class ClientesController implements Serializable {

    @EJB
    private com.ventas.controlador.ClientesFacade ejbFacade;
    private List<Clientes> items = null;
    private Clientes selected;
    private MapModel simpleModel;

    public ClientesController() {
    }

    public Clientes getSelected() {
        return selected;
    }

    public void setSelected(Clientes selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ClientesFacade getFacade() {
        return ejbFacade;
    }

    public Clientes prepareCreate() {
        selected = new Clientes();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ClientesCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ClientesUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ClientesDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Clientes> getItems() {     
        if (items == null) {
              items = getFacade().findAll();
            }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction == PersistAction.DELETE) {
                    getFacade().remove(selected);
                } else {
                    if (persistAction == PersistAction.CREATE){
                        getFacade().create(selected);
                    }else{
                        getFacade().edit(selected);
                    }
                }
                JsfUtil.addSuccessMessage(successMessage);
            }catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Clientes getClientes(java.math.BigDecimal id) {
        return getFacade().find(id);
    }

    public List<Clientes> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Clientes> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Clientes.class)
    public static class ClientesControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ClientesController controller = (ClientesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "clientesController");
            return controller.getClientes(getKey(value));
        }

        java.math.BigDecimal getKey(String value) {
            java.math.BigDecimal key;
            key = new java.math.BigDecimal(value);
            return key;
        }

        String getStringKey(java.math.BigDecimal value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Clientes) {
                Clientes o = (Clientes) object;
                return getStringKey(o.getIdCliente());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Clientes.class.getName()});
                return null;
            }
        }

    }
    
    //Este es el código que toma los puntos del mapa
    public void onPointSelect(PointSelectEvent event) {
        LatLng latlng = event.getLatLng();        
        addMessage(new FacesMessage(FacesMessage.SEVERITY_INFO, "Punto Seleccionado", "Latitud:" + latlng.getLat() + ", Longitud:" + latlng.getLng()));
    }
      
    public void addMessage(FacesMessage message) {
        FacesContext.getCurrentInstance().addMessage(null, message);
    }        
    
    @PostConstruct
    public void init() {
        simpleModel = new DefaultMapModel();
        
        items = getFacade().findAll();
        
        for(Clientes mauro: items){
            LatLng coord1 = new LatLng(mauro.getFloatlatitud(), mauro.getFloatlongitud());
            simpleModel.addOverlay(new Marker(coord1, mauro.getNombreCliente()));
        }

    }
    
    public MapModel getSimpleModel() {
        return simpleModel;
    }    

}

src/java/com/ventas/controlador/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.controlador;


import com.javapapers.java.social.facebook.FBConnection;
import com.ventas.entidades.Usuario;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
// el siguiente import es para MD5 cifrar password
//import org.apache.commons.codec.digest.DigestUtils;


/**
 *
 * @author Mauro
 */
@Named(value = "loginController")
@SessionScoped
public class LoginController implements Serializable {

    /**
     * Creates a new instance of LoginController
     */
    
    @EJB // Esto es lo que hace que se inyecte y se pueda conectar con la BD
    // Usuario para poder conectar a la base de datos
    private UsuarioFacade usuarioFacade; // se deja privado sin hacer Get and Setter, 
    //para evitar que una persona se conecte desde el index a la BD, se llama relación fuerte
       
    private String login;
    private String password;
    private Usuario usuarioLogueado;
    private FBConnection conectionFb=new FBConnection();

    public Usuario getUsuarioLogueado() {
        return usuarioLogueado;
    }

    public void setUsuarioLogueado(Usuario usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public LoginController() {
    }
    
    /*public String cifrarPassword(String Password){
        passwordCifrado = DigestUtils.md5Hex(password);
        return passwordCifrado;
    }*/
    
    
    public String autenticarUsuario(){  
        /*if (login.equals("mmosquera") && password.equals("123")){     
            return "acceder";
        }*/
        Usuario usuarioEncontrado= usuarioFacade.obtenerUsuarioxNombre(login);
        
        if(usuarioEncontrado!=null){
            
            if(usuarioEncontrado.getPasswordUsuario().equals(password)){
                usuarioLogueado=usuarioEncontrado;
                FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("username", login);
                return "acceder";
            }else{     
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage
                (FacesMessage.SEVERITY_ERROR,"Password Errado","Password Errado"));
            } 
                
        }else{
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage
            (FacesMessage.SEVERITY_ERROR,"Nombre No Existe","Nombre No Existe"));
        }
        
        return null;
    }
    
    public String getObtenerConexionFb(){
        
        //FBConnection fbprueba = new FBConnection();
        //FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("username","facebook");
        return conectionFb.getFBAuthUrl();
    }
    public String cerrarSesion(){
        
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().clear();
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        
        return "loginPage";
    }
}

web/ventas/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="VentasCreateDlg" widgetVar="VentasCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateVentasTitle}">
            <h:form id="VentasCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{ventasController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateVentasLabel_idVenta}" for="idVenta" />
                        <p:inputText id="idVenta" value="#{ventasController.selected.idVenta}" title="#{bundle.CreateVentasTitle_idVenta}" required="true" requiredMessage="#{bundle.CreateVentasRequiredMessage_idVenta}"/>
                        <p:outputLabel value="#{bundle.CreateVentasLabel_cantidadVenta}" for="cantidadVenta" />
                        <p:inputText id="cantidadVenta" value="#{ventasController.selected.cantidadVenta}" title="#{bundle.CreateVentasTitle_cantidadVenta}" />
                        <p:outputLabel value="#{bundle.CreateVentasLabel_idFactura}" for="idFactura" />
                        <p:selectOneMenu id="idFactura" value="#{ventasController.selected.idFactura}" >
                            <f:selectItems value="#{facturasController.itemsAvailableSelectOne}"
                                           var="idFacturaItem"
                                           itemValue="#{idFacturaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateVentasLabel_idProducto}" for="idProducto" />
                        <p:selectOneMenu id="idProducto" value="#{ventasController.selected.idProducto}" >
                            <f:selectItems value="#{productosController.itemsAvailableSelectOne}"
                                           var="idProductoItem"
                                           itemValue="#{idProductoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{ventasController.create}" value="#{bundle.Save}" update="display,:VentasListForm:datalist,:growl" oncomplete="handleSubmit(args,'VentasCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" immediate="true" onclick="VentasCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/ventas/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="VentasEditDlg" widgetVar="VentasEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditVentasTitle}">
            <h:form id="VentasEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{ventasController.selected != null}">
                        <p:outputLabel value="#{bundle.EditVentasLabel_idVenta}" for="idVenta" />
                        <p:inputText id="idVenta" value="#{ventasController.selected.idVenta}" title="#{bundle.EditVentasTitle_idVenta}" required="true" requiredMessage="#{bundle.EditVentasRequiredMessage_idVenta}"/>
                        <p:outputLabel value="#{bundle.EditVentasLabel_cantidadVenta}" for="cantidadVenta" />
                        <p:inputText id="cantidadVenta" value="#{ventasController.selected.cantidadVenta}" title="#{bundle.EditVentasTitle_cantidadVenta}" />
                        <p:outputLabel value="#{bundle.EditVentasLabel_idFactura}" for="idFactura" />
                        <p:selectOneMenu id="idFactura" value="#{ventasController.selected.idFactura}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{facturasController.itemsAvailableSelectOne}"
                                           var="idFacturaItem"
                                           itemValue="#{idFacturaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditVentasLabel_idProducto}" for="idProducto" />
                        <p:selectOneMenu id="idProducto" value="#{ventasController.selected.idProducto}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{productosController.itemsAvailableSelectOne}"
                                           var="idProductoItem"
                                           itemValue="#{idProductoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{ventasController.update}" value="#{bundle.Save}" update="display,:VentasListForm:datalist,:growl" oncomplete="handleSubmit(args, 'VentasEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="VentasEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/ventas/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListVentasTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="VentasListForm">
                <p:panel header="#{bundle.ListVentasTitle}">
                    <p:dataTable id="datalist" value="#{ventasController.items}" var="item"
                                 selectionMode="single" selection="#{ventasController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idVenta}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentasTitle_idVenta}"/>
                            </f:facet>
                            <h:outputText value="#{item.idVenta}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentasTitle_cantidadVenta}"/>
                            </f:facet>
                            <h:outputText value="#{item.cantidadVenta}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentasTitle_idFactura}"/>
                            </f:facet>
                            <h:outputText value="#{item.idFactura.toString()}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentasTitle_idProducto}"/>
                            </f:facet>
                            <h:outputText value="#{item.idProducto.toString()}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton disabled="#{loginController.usuarioLogueado.idTipoUsuario.idTipoUsuario==3}" id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{ventasController.prepareCreate}" update=":VentasCreateForm" oncomplete="PF('VentasCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":VentasViewForm" oncomplete="PF('VentasViewDialog').show()" disabled="#{empty ventasController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":VentasEditForm" oncomplete="PF('VentasEditDialog').show()" disabled="#{empty ventasController.selected}"/>
                            
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{ventasController.destroy}" update=":growl,datalist" disabled="#{empty ventasController.selected}">
                            <p:confirm header="Confirmation" message="Desea Eliminar Este Registro?" icon="ui-icon-alert"/>                            
                            </p:commandButton>
                            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                <p:commandButton value="SI" type="button"  styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                                <p:commandButton value="NO" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                            </p:confirmDialog>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/ventas/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="VentasViewDlg" widgetVar="VentasViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewVentasTitle}">
            <h:form id="VentasViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{ventasController.selected != null}">
                        <h:outputText value="#{bundle.ViewVentasLabel_idVenta}"/>
                        <h:outputText value="#{ventasController.selected.idVenta}" title="#{bundle.ViewVentasTitle_idVenta}"/>
                        <h:outputText value="#{bundle.ViewVentasLabel_cantidadVenta}"/>
                        <h:outputText value="#{ventasController.selected.cantidadVenta}" title="#{bundle.ViewVentasTitle_cantidadVenta}"/>
                        <h:outputText value="#{bundle.ViewVentasLabel_idFactura}"/>
                        <h:outputText value="#{ventasController.selected.idFactura}" title="#{bundle.ViewVentasTitle_idFactura}"/>
                        <h:outputText value="#{bundle.ViewVentasLabel_idProducto}"/>
                        <h:outputText value="#{ventasController.selected.idProducto}" title="#{bundle.ViewVentasTitle_idProducto}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="VentasViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>