src/java/com/ventas/controlador/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.controlador;


import com.javapapers.java.social.facebook.FBConnection;
import com.ventas.entidades.Usuario;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
// el siguiente import es para MD5 cifrar password
//import org.apache.commons.codec.digest.DigestUtils;


/**
 *
 * @author Mauro
 */
@Named(value = "loginController")
@SessionScoped
public class LoginController implements Serializable {

    /**
     * Creates a new instance of LoginController
     */
    
    @EJB // Esto es lo que hace que se inyecte y se pueda conectar con la BD
    // Usuario para poder conectar a la base de datos
    private UsuarioFacade usuarioFacade; // se deja privado sin hacer Get and Setter, 
    //para evitar que una persona se conecte desde el index a la BD, se llama relación fuerte
       
    private String login;
    private String password;
    private Usuario usuarioLogueado;
    private FBConnection conectionFb=new FBConnection();

    public Usuario getUsuarioLogueado() {
        return usuarioLogueado;
    }

    public void setUsuarioLogueado(Usuario usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public LoginController() {
    }
    
    /*public String cifrarPassword(String Password){
        passwordCifrado = DigestUtils.md5Hex(password);
        return passwordCifrado;
    }*/
    
    
    public String autenticarUsuario(){  
        /*if (login.equals("mmosquera") && password.equals("123")){     
            return "acceder";
        }*/
        Usuario usuarioEncontrado= usuarioFacade.obtenerUsuarioxNombre(login);
        
        if(usuarioEncontrado!=null){
            
            if(usuarioEncontrado.getPasswordUsuario().equals(password)){
                usuarioLogueado=usuarioEncontrado;
                FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("username", login);
                return "acceder";
            }else{     
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage
                (FacesMessage.SEVERITY_ERROR,"Password Errado","Password Errado"));
            } 
                
        }else{
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage
            (FacesMessage.SEVERITY_ERROR,"Nombre No Existe","Nombre No Existe"));
        }
        
        return null;
    }
    
    public String getObtenerConexionFb(){
        
        //FBConnection fbprueba = new FBConnection();
        //FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("username","facebook");
        return conectionFb.getFBAuthUrl();
    }
    public String cerrarSesion(){
        
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().clear();
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        
        return "loginPage";
    }
}

web/clientePlantilla.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <body>

        <ui:composition template="./templatePrincipal.xhtml">

            <ui:define name="top">
   
                
            </ui:define>

            <ui:define name="left">
                left
            </ui:define>

            <ui:define name="right">
                right
            </ui:define>

            <ui:define name="content">
                content
            </ui:define>

            <ui:define name="bottom">
                bottom
            </ui:define>

        </ui:composition>

    </body>
</html>

web/comunicacion_facebook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Prueba de Funcionamiento
        <h:outputText value="#{comunicacionFaceBook.codigo}"/>
        <!--<h:outputText value="#{comunicacionFaceBook.nombre}"/>-->
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="welcomePrimefaces" value="Primefaces welcome page" />
        <br />
        <h:link outcome="/categorias/List" value="Show All Categorias Items"/>
        <br />
        <h:link outcome="/clientes/List" value="Show All Clientes Items"/>
        <br />
        <h:link outcome="/facturas/List" value="Show All Facturas Items"/>
        <br />
        <h:link outcome="/productos/List" value="Show All Productos Items"/>
        <br />
        <h:link outcome="/proveedores/List" value="Show All Proveedores Items"/>
        <br />
        <h:link outcome="/ventas/List" value="Show All Ventas Items"/>
        <br />
        <h:link outcome="/tipoUsuario/List" value="Show All TipoUsuario Items"/>
        <br />
        <h:link outcome="/usuario/List" value="Show All Usuario Items"/>
    </h:body>








</html>

web/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Inicio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        <link type="text/css" rel="stylesheet" href="#{facesContext.externalContext.requestContextPath}/resources/css/materialize.min.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACxjYynTIX7ERT3ZHdCwY9HMWcYZ7hOHs" 
                            type="text/javascript"></script>
        <!--<META HTTP-EQUIV="refresh" CONTENT="15"></META>-->
        
    </h:head>
    
    <h:body> 
        <h:form>
            
            <p:growl id="pgErrores"/> <!-- para poder que salgan los mensajes de las cajas de tecto-->
            <p:panel>
                    <div class="card-panel indigo lighten-1"><center><h6>Empresa Ventas</h6></center></div>                        
                
                    <!--<p:contentFlow value="#{imagesView.images}" var="image">
                    <p:graphicImage name="images/#{image}" styleClass="content" />-->
                    <!--<div class="caption">#{image}</div>-->
                    <!--</p:contentFlow>-->
                    <center>
                    <p:gmap center="5.076762, -75.519534" zoom="17" type="HYBRID" style="width:70%;height:300px" />
                    </center>
                    

                    <div class="container">                    
                        <div class="indigo lighten-1">  
                            <div class="row">    
                            <div class="col s4 offset-s2">
                            <p:outputLabel for="pitUsuario" value="#{bundle.boton_login}"/>
                            <p:inputText id="pitUsuario" maxlength="20" required="true" value="#{loginController.login}"/>
                            </div>
                            <div class="col s4">
                            <p:outputLabel for="pitContraseña" value="#{bundle.boton_password}"/>
                            <p:password id="pitContraseña" required="true" value="#{loginController.password}"/>                                  
                            </div>
                            </div>    
                        </div>    
                    </div>
                
                    <p:growl id="messages" />
                    
                    <div class="container"> 
                    <div class="row">
                        <div class="col s6 offset-s5">
                            <p:splitButton value="#{bundle.boton1}" action="#{loginController.autenticarUsuario()}" update="@all" icon="ui-icon-disk">
                                <redirect />
                                <p:menuitem value="#{bundle.boton1_opc1}" url="http://www.google.com" icon="ui-icon-arrowrefresh-1-w" />
                                <p:separator />
                                <p:menuitem value="#{bundle.boton1_opc2}" url="http://www.umanizales.edu.co" icon="ui-icon-arrowrefresh-1-w" />
                            </p:splitButton>                
                            <!--<p:commandButton value="Ingresar" action="acceder" update="@all"/>-->                
                        </div>
                    </div>
                    </div>      
                    
                    <div class="row">
                        <div class="col s2 offset-s5">
                            <h:outputLink value="#{loginController.obtenerConexionFb}">                               
                                <h:graphicImage class="responsive-img" url="/img/facebookloginbutton2.png"></h:graphicImage>
                            </h:outputLink>
                            
                        </div>
                    </div>                        
                    
            </p:panel>                              
        </h:form>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/resources/js/materialize.min.js"></script>
    </h:body>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>    
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
        <h:outputScript library="js" name="jsfcrud.js"/>
        <ui:insert name="head"/>
    </h:head>

    <h:body>
        <p:growl id="growl" life="3000" />

        <p:layout fullPage="true" >
            <p:layoutUnit position="north" size="65" header="#{bundle.AppName}">
                <h:form id="menuForm">
                    <p:menubar>
                        <p:menuitem value="#{bundle.Home}" outcome="/index" icon="ui-icon-home"/>
                        <p:submenu label="#{bundle.Maintenance}">
                            <p:menuitem rendered="#{loginController.usuarioLogueado.idTipoUsuario.idTipoUsuario==1}" value="Categorias" outcome="/categorias/List.xhtml" />
                            <p:menuitem value="Clientes" outcome="/clientes/List.xhtml" />
                            <p:menuitem value="Facturas" outcome="/facturas/List.xhtml" />
                            <p:menuitem value="Productos" outcome="/productos/List.xhtml" />
                            <p:menuitem value="Proveedores" outcome="/proveedores/List.xhtml" />
                            <p:menuitem value="Ventas" outcome="/ventas/List.xhtml" />
                            <p:menuitem rendered="#{loginController.usuarioLogueado.idTipoUsuario.idTipoUsuario!=3}" value="Usuarios" outcome="/usuario/List.xhtml" />
                            <p:menuitem rendered="#{loginController.usuarioLogueado.idTipoUsuario.idTipoUsuario!=3}" value="Tipo Usuarios" outcome="/tipoUsuario/List.xhtml" />
                        </p:submenu>
                        <p:submenu label="#{bundle.reports}">
                            <p:menuitem value="Productos VS Cantidad" outcome="/reportes/productosPrecios.xhtml"/>
                            <p:menuitem value="Productos X Proveedor" outcome="/reportes/productosProveedor.xhtml"/>
                            <p:menuitem value="Productos X Categoria" outcome="/reportes/productosCategoria.xhtml"/>
                            <p:menuitem value="Consulta Dinamica" outcome="/reportes/consulta.xhtml"/>
                        </p:submenu>
                        <p:menuitem value="#{loginController.usuarioLogueado.correoUsuario}"/>
                        <p:menuitem action="#{loginController.cerrarSesion()}">Cerrar Sesión</p:menuitem>
                    </p:menubar>
                </h:form>
            </p:layoutUnit>

            <p:layoutUnit position="south" size="60">
                <ui:insert name="footer"/>
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <ui:insert name="body"/>
            </p:layoutUnit>

        </p:layout>
 
    </h:body>
    <!--
    <h:panelGroup rendered="#{loginController.usuarioLogueado==null}">
            <h:outputLabel><center><h1>Ni lo intente no sirve, sin login</h1></center></h:outputLabel>            
    </h:panelGroup>
    -->
</html>

web/templatePrincipal.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">Top</ui:insert>
        </div>
        <div>
            <div id="left">
                <ui:insert name="left">Left</ui:insert>
            </div>
            <div>
                <div id="right">
                    <ui:insert name="right">Right</ui:insert>
                </div>
                <div id="content" class="right_content">
                    <ui:insert name="content">Content</ui:insert>
                </div>
            </div>
        </div>
        <div id="bottom">
            <ui:insert name="bottom">Bottom</ui:insert>
        </div>

    </h:body>

</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>